on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job of Cutom Github Action
    steps:
      - name: Custom Github Action
        id: hello
        uses: darshitsri/github_actions_test@v1
        with:
          who-to-greet: 'Hello Team this my Own GITHUB ACTION'
      - name: Get the output time
        run: echo "The time was ${{ steps.hello.outputs.time }}"
